[package]
name = "rovcommand"
version = "0.1.0"
authors = ["Craig Joly <craig@snowkeep.ca>"]

[dependencies]
piston_window = "0.64.0"
find_folder = "0.3.0"
piston2d-graphics = "0.21.1"

[dependencies.conrod]
version = "0.51.1"
features = ["piston"]
